# Use Node.js version 21 as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application's source code
COPY . .

# Expose the port your app runs on
EXPOSE 3001

# Set environment variables
ENV JWT_SECRET_KEY=xxx
ENV MONGO_URL=xxx

# Use nodemon to run your application
CMD ["npm", "start"]